apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

images:
- name: nginx
  newName: nginx
  newTag: latest
  # This updates the nginx image to a newer version for the development environment.