apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: stage-

images:
- name: nginx
  newName: nginx
  newTag: stable
  # This updates the nginx image to a specific version for the staging environment.